--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is raised when the enchanting menu determines the spell point cost of the current enchantment. Modifying this value affects the displayed enchantment cost, the derived cast/charge use values, the self-enchant success chance, and the base value used for enchanting service pricing.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/calcEnchantingSpellPointCost).
--- @class calcEnchantingSpellPointCostEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field castType tes3.enchantmentType *Read-only*. The enchantment cast type. Maps to `tes3.enchantmentType.*`.
--- @field effects table[] *Read-only*. An array of the effects being enchanted onto the item. This includes the `effect` object, `magnitudeLow`/`magnitudeHigh` values, the `area`, `duration`, and `range`. The `attribute` and `skill` values are available as appropriate.
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3item|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon *Read-only*. The item, if any, that is being enchanted.
--- @field itemData tes3itemData *Read-only*. The item data for the enchanted item.
--- @field mobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor offering enchanting services. May not always be available.
--- @field reference tes3reference *Read-only*. A shortcut to the mobile's reference. May not always be available.
--- @field soul tes3actor|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3npc|tes3npcInstance *Read-only*. The soul contained in the soul gem.
--- @field soulGem tes3misc *Read-only*. The soul gem being used to make the enchantment.
--- @field soulGemData tes3itemData *Read-only*. The soul gem's associated item data.
--- @field spellPointCost number The total spell point cost of the enchantment. This can be modified.
