--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is triggered before a magic absorption check. It allows changing the absorption chance.
--- 
--- Each spell absorption effect active on a target will roll separately; the absorb chances are independent. This event also occurs once per effect in a spell, so a multi-effect spell may trigger this multiple times.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/magicAbsorb).
--- @class magicAbsorbEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field absorbChance number The % chance that the magic is absorbed. May be modified.
--- @field absorbEffect tes3activeMagicEffect *Read-only*. The specific spell absorption effect being tested. This is a `tes3activeMagicEffect` instead of a more common magic instance. You can lookup the magic source instance or effect instance with `tes3activeMagicEffect` accessors.
--- @field effectIndex number *Read-only*. The effect index into the `source` effect list that is being tested against.
--- @field mobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor that may absorb the spell.
--- @field source tes3alchemy|tes3enchantment|tes3spell *Read-only*. The magic source.
--- @field sourceInstance tes3magicSourceInstance *Read-only*. The unique instance of the magic source.
--- @field target tes3reference *Read-only*. The actor that may absorb the spell.
