--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A handle to safely operate on [tes3object](https://mwse.github.io/MWSE/types/tes3object/).
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/types/mwseSafeObjectHandle).
--- @class mwseSafeObjectHandle
mwseSafeObjectHandle = {}

--- Returns the object of this handle.
--- @return tes3activator|tes3alchemy|tes3apparatus|tes3armor|tes3baseObject|tes3birthsign|tes3bodyPart|tes3book|tes3cell|tes3class|tes3clothing|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3dialogue|tes3dialogueInfo|tes3door|tes3enchantment|tes3faction|tes3gameSetting|tes3globalVariable|tes3ingredient|tes3land|tes3landTexture|tes3leveledCreature|tes3leveledItem|tes3light|tes3lockpick|tes3magicSourceInstance|tes3misc|tes3npc|tes3npcInstance|tes3pathGrid|tes3probe|tes3quest|tes3race|tes3reference|tes3region|tes3repairTool|tes3script|tes3skill|tes3sound|tes3soundGenerator|tes3spell|tes3startScript|tes3static|tes3weapon|nil result No description yet available.
function mwseSafeObjectHandle:getObject() end

--- Returns true if the object of this handle is still valid. Invalid objects no longer exist or were deleted.
--- @return boolean valid No description yet available.
function mwseSafeObjectHandle:valid() end

