--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Internal data for a mobile object's active spell or internal light.
--- @class tes3mobileObjectLightData
--- @field light niPointLight|niSpotLight|nil *Read-only*. The point light currently backing this mobile light entry.
--- @field radius number The current light radius used to calculate the spell light's attenuation.
