--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A pair of vectors marking a bounding box.
--- 	
--- !!! warning "Bounding boxes will always be centered at the world origin."
--- 	i.e., their midpoint will always be `(0,0,0)`. You may want to offset the `min` and `max` of the bounding box by a specified position before using them.
--- 
--- @class tes3boundingBox
--- @field max tes3vector3 The maximum bound of the box.
--- @field min tes3vector3 The minimum bound of the box.
tes3boundingBox = {}

--- Converts the bounding box to a string with 2 decimal places. The minimum bounds are printed first, then the maximal bounds.
--- @return string result No description yet available.
function tes3boundingBox:__tostring() end

--- Clamps a given point into the bounding box, given an origin.
--- @param point tes3vector3 The point to clamp. It is modified as part of this method call.
--- @param origin tes3vector3 The origin to offset the minimum/maximum vectors by.
--- @return boolean result No description yet available.
function tes3boundingBox:clampPoint(point, origin) end

--- Creates a copy of the bounding box.
--- @return tes3boundingBox result No description yet available.
function tes3boundingBox:copy() end

--- Checks to see if any of the vertices in the bounding box remain at a minimum/maximum after a call to `:initialize()`.
--- @return boolean result No description yet available.
function tes3boundingBox:hasUninitializedData() end

--- Resets the bounding box so that the minimum and maximum values are set to their maximum opposites. Useful when recalculating the bounding box.
function tes3boundingBox:initialize() end

--- Returns a table containing the 8 vertices comprising this bounding box.
--- @return tes3vector3[] result No description yet available.
function tes3boundingBox:vertices() end

